---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  tags: apache, apache2
  become: true
  tasks:
  
  - name: install apache and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes  
  
  - name: copy default html file for site
    tags: apache, apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: install db package (Ubuntu)
      tags: db
      package:
        name: 
          - "{{ db_package }}"
        state: latest
        update_cache: yes


- hosts: file_servers
  tags: file
  become: true
  tasks:

    - name: install samba package
      tags: samba
      package:
        name:
          - "{{ samba_package }}"
        state: latest
        update_cache: yes
